export ZSH=${HOME}/.oh-my-zsh
# ZSH_THEME="bullet-train"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
autoload -Uz compinit
compinit
HISTFILE=~/.histfile
HISTSIZE=25000
SAVEHIST=25000
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

plugins=(
  git
  docker
  aws
  pip
  python
  node
  zsh-autosuggestions
)

BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  dir
  git
  screen
  perl
  ruby
  virtualenv
  nvm
  aws
  go
  rust
  elixir
  hg
  cmd_exec_time
)

# Source $ZSH/oh-my-zsh.sh

source ${HOME}/.local/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundle qoomon/zsh-lazyload
antigen bundle git
antigen bundle aws
antigen bundle docker
antigen bundle pip
antigen bundle python
antigen bundle node
antigen bundle zsh-autosuggestions
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme romkatv/powerlevel10k
# antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

# Tell Antigen that you're done.
antigen apply

for file in ~/.{aliases,functions,path,extra,exports}; do
  [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file"
done
unset file

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
