actions:
## SSH Keys
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/.ssh
  - action: command.run
    command: ssh-keygen
    args:
      - "-t"
      - ed25519
      - "-f"
      - "-N ''"
      - {{ user.home_dir }}.ssh/git
  - action: command.run
    command: ssh-keygen
    args:
      - "-t"
      - ed25519
      - "-f"
      - "-N ''"
      - {{ user.home_dir }}/.ssh/id
  ## System Upgrade
  - action: command.run
    command: yay
    args:
      - "-Syyu"