depends:
  - 1-init
  - 2-packages
  - 3-services
  - 4-node
  - 4-python
  - 4-ruby
  - 4-rust
actions:
  - action: file.copy
    from: alacritty/alacritty.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/alacritty.yml"
  - action: file.copy
    from: alacritty/colors.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/colors.yml"
  - action: file.copy
    from: alacritty/fonts.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/fonts.yml"
