depends:
  - 2-packages
actions:
  - action: file.copy
    from: alacritty/alacritty.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/alacritty.yml"
  - action: file.copy
    from: alacritty/colors.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/colors.yml"
  - action: file.copy
    from: alacritty/fonts.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/fonts.yml"
  - action: file.copy
    from: hyper/hyper.js
    template: true
    to: "{{ user.home_dir }}/.hyper.js"