depends:
  - 1-init
  - 2-packages
  - 3-services
actions:
  - action: file.copy
    from: gitignore
    to: "{{ user.home_dir }}/.gitignore"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - user.name
      - "{{ variables.userFullName }}"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - user.email
      - "{{ variables.userEmail }}"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - core.editor
      - nvim
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - core.editor
      - nvim
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - core.autocrlf
      - input
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - core.whitespace
      - "fix,-indent-with-non-tab,trailing-space,cr-at-eol"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - core.excludesfile
      - "~/.gitignore"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - web.browser
      - "brave"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - push.default
      - "current"
  - action: command.run
    command: git
    args:
      - config
      - "--global"
      - credential.helper
      - "cache --timeout=3600"
